spring:
    application:
        name: kafka-base
    # kafka连接信息 ip+port
    kafka:
        bootstrap-servers: 124.222.92.239:9092

        # 配置生产者
#        producer:
        # 配置消费者
#        consumer